def generate_arithemetic_exception():
    print("Generating Arithemetic Exception...")
    a = 16
    b = 0
    result = a / b
    print("Result:",result)

def main():
    generate_arithemetic_exception()

main()
